version: "3.7"

services:

  # local prometheus setup is a temporary solution that may be removed
  # after centralized cluster-wide prometheus is deployed
  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-volume:/var/lib/prometheus/data
    networks:
      - test
    ports:
      - "9093:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # local grafana setup is a temporary solution that may be removed
  # after centralized cluster-wide grafana is deployed
  grafana:
    image: grafana/grafana:latest
    user: "0"
    volumes:
      - grafana-volume:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - test
    ports:
      - "3000:3000"

volumes:
  prometheus-volume:
  grafana-volume:

networks:
  test:
    driver: bridge