feign:
  client:
    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: FULL
      jplaceholder:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL

logging:
  level:
    com.educational.clients: DEBUG