server:
#  random port
#  port: 0
  port: 8990
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery:
          timeout:
            ms: 10000
        linger:
          ms: 5000
        request:
          timeout:
            ms: 5000
#      не рекомендуется настраивать через retry и backoff
#      retries: 10
#      properties:
#        retry:
#          backoff:
#            ms: 1000
        enable:
          idempotence: true
        max.in.flight:
          requests.per.connection: 5