---
# local prometheus setup is a temporary solution that may be removed
# after centralized cluster-wide prometheus is deployed
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:8082', 'host.docker.internal:8083' ]